services:
  localdb:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user

  testdb:
    image: postgres:15.1
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=admin_test
      - POSTGRES_PASSWORD=root_test
      - POSTGRES_DB=user_test
